language: bash

services:
- docker

env:
  matrix:
  - PYTHON_VER=3.7
  - PYTHON_VER=3.6
  - PYTHON_VER=3.5 GITHUB_RELEASE=1

script:
- set -e
- make test
- cp docker.mk Makefile
- tar -czf docker4python.tar.gz Dockerfile docker-compose.yml docker-sync.yml Makefile .env traefik.yml

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
  - docker4python.tar.gz
  on:
    tags: true
    condition: $GITHUB_RELEASE = 1

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
